name: deploy-pr

on:
  pull_request:
    paths:
      - 'app/**'
      - .github/workflows/deploy-pr.yml

env: 
  REGISTEY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTEY}}/${{ github.repository }}

      - name: log in to github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTEY}}
          username: ${{ github.actor }}
          password: ${{ github.GITHUB_TOKEN }}
    
      - name: build and push
        uses: docker/build-and-action@v6
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
